### ISSUE TITLE
can't use scss

### ISSUE THREAD

**Issue by RezaAhmadi0117** [MahdiMajidzadeh/bootstrap-v4-rtl#47]
hi
i wanna use npm to use bootstrap rtl but give me this error: 

/////////////////////////////////////////////////////////////////////////

`ERROR in ./resources/sass/bootstrap-rtl.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
       ^
      Can't find stylesheet to import.
  ╷
2 │ @import '/node_modules/bootstrap-v4-rtl/scss/bootstrap-rtl';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  stdin 2:9  root stylesheet
      in C:\Users\reza\Desktop\laravel\resources\sass\bootstrap-rtl.scss (line 2, column 9)
    at runLoaders (C:\Users\reza\Desktop\laravel\node_modules\webpack\lib\NormalModule.js:313:20)
    at C:\Users\reza\Desktop\laravel\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\reza\Desktop\laravel\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\reza\Desktop\laravel\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at render (C:\Users\reza\Desktop\laravel\node_modules\sass-loader\lib\loader.js:52:13)
    at Function.call$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:53443:16)
    at _render_closure1.call$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:33267:12)
    at _RootZone.runBinary$3$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19664:18)
    at _RootZone.runBinary$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19668:19)
    at _FutureListener.handleError$1 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18136:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18421:40)
    at Object._Future__propagateToListeners (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:3470:88)
    at _Future._completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18257:9)
    at _SyncCompleter._completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18123:19)
    at _SyncCompleter.completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18092:12)
    at _AsyncAwaitCompleter.completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:17629:25)
    at Object._asyncRethrow (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:3226:17)
    at C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:10407:20
    at _wrapJsFunctionForAsync_closure.$protected (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:3249:15)
    at _wrapJsFunctionForAsync_closure.call$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:17664:12)
    at _awaitOnObject_closure0.call$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:17656:25)
    at _RootZone.runBinary$3$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19664:18)
    at _RootZone.runBinary$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19668:19)
    at _FutureListener.handleError$1 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18136:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18421:40)
    at Object._Future__propagateToListeners (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:3470:88)
    at _Future._completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18257:9)
    at _SyncCompleter._completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18123:19)
    at _SyncCompleter.completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18092:12)
    at Object.eval (eval at Closure_forwardCallTo (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:1515:14), <anonymous>:3:41)
    at _RootZone.runBinary$3$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19664:18)
    at _RootZone.runBinary$3 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:19668:19)
    at _FutureListener.handleError$1 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18136:19)
    at _Future__propagateToListeners_handleError.call$0 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18421:40)
    at Object._Future__propagateToListeners (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:3470:88)
    at _Future._completeError$2 (C:\Users\reza\Desktop\laravel\node_modules\sass\sass.dart.js:18257:9)
 @ ./resources/sass/bootstrap-rtl.scss

ERROR in ./resources/sass/bootstrap-rtl.scss (./node_modules/css-loader??ref--7-2!./node_modules/postcss-loader/src??postcss2!./node_modules/resolve-url-loader??ref--7-4!./node_modules/sass-loader/lib/loader.js??ref--7-5!./resources/sass/bootstrap-rtl.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
       ^
      Can't find stylesheet to import.
  ╷
2 │ @import '/node_modules/bootstrap-v4-rtl/scss/bootstrap-rtl';
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reza\AppData\Roaming\npm-cache\_logs\2019-08-05T07_18_02_681Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reza\AppData\Roaming\npm-cache\_logs\2019-08-05T07_18_02_756Z-debug.log`

/////////////////////////////////////////////////////////////////

i can use bootstrap v4 with npm and it is compiled with scss but with rtl module no.

**Comment by MahdiMajidzadeh** [comment]
This issue is for dependencies

**Comment by MahdiMajidzadeh** [comment]
and it's fixed now
